GET http://localhost:8080/books
###

GET http://localhost:8080/books/6469ad834ff7ef6583f8f092
###

###
POST http://localhost:8080/books HTTP/1.1
content-type: application/json

{
    "name": "Testing",
    "author": "Steven Valencia",
    "isbn": "51996018565",    
    "language": "spanish",
    "date": "2023",
    "funfact": "testing facts"
}

### UPDATE BOOK

PUT http://localhost:8080/books/646ae7aa07f51e0774056dae HTTP/1.1
content-type: application/json

{
    "name": "Testing",
    "author": "Steven Valencia",
    "isbn": "51996018565",    
    "language": "spanish",
    "date": "2023",
    "funfact": "testing facts"
}

### DELETE BOOK

DELETE http://localhost:8080/books/646ae7aa07f51e0774056dae HTTP/1.1




### RENDER

GET https://cse341-project-2-rx9t.onrender.com/books 
###

GET https://cse341-project-2-rx9t.onrender.com/books/6469ad834ff7ef6583f8f092
###

###
POST https://cse341-project-2-rx9t.onrender.com/books HTTP/1.1
content-type: application/json

{
    "name": "Testing",
    "author": "Steven Valencia",
    "isbn": "51996018565",    
    "language": "spanish",
    "date": "2023",
    "funfact": "testing facts"
}

###
PUT http://cse341-project-2-rx9t.onrender.com/books/646ae7aa07f51e0774056dae HTTP/1.1
content-type: application/json

{
    "name": "Testing",
    "author": "Steven Valencia",
    "isbn": "51996018565",    
    "language": "spanish",
    "date": "2023",
    "funfact": "testing facts"
}

### DELETE BOOK

DELETE http://cse341-project-2-rx9t.onrender.com/books/646ae7aa07f51e0774056dae HTTP/1.1